FROM node:20-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source
COPY . . 

# Expose app port
EXPOSE 3000

# Start app 
CMD ["npm", "start"]