# =========================
# Stage 1 - Build Stage
# =========================

# From base image
FROM eclipse-temurin:17-jdk-alpine AS builder

# Create a working directory
WORKDIR /web

# Copy source code into container 
COPY src/Main.java .

# Compile the Java application
RUN javac Main.java

# =========================
# Stage 2 - Runtime Stage
# =========================

# From base image
FROM eclipse-temurin:17-jre-alpine

# Set working directory
WORKDIR /app

# Copy only compiled class from builder stage
COPY --from=builder /web/Main.class .

# Run the application
CMD ["java", "Main"]

